// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_H7CD60zbfl5vRxBhHc257epTAFAU7qg',
    appId: '1:615072854096:web:7bc77c1a3de1ec1a86e155',
    messagingSenderId: '615072854096',
    projectId: 'outdoor-53765',
    authDomain: 'outdoor-53765.firebaseapp.com',
    storageBucket: 'outdoor-53765.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX8BCT-d8qiTnruqqzsyTmsRsXcEFwJ1c',
    appId: '1:615072854096:android:37886583012a3cf286e155',
    messagingSenderId: '615072854096',
    projectId: 'outdoor-53765',
    storageBucket: 'outdoor-53765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcvRpEroTNtQZbCPwBKlgQc-UfiE1062c',
    appId: '1:615072854096:ios:633eb0162451eb9686e155',
    messagingSenderId: '615072854096',
    projectId: 'outdoor-53765',
    storageBucket: 'outdoor-53765.appspot.com',
    iosClientId: '615072854096-0mmann1tbsit6ruljap0vteir3ageot1.apps.googleusercontent.com',
    iosBundleId: 'com.example.outdoor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcvRpEroTNtQZbCPwBKlgQc-UfiE1062c',
    appId: '1:615072854096:ios:633eb0162451eb9686e155',
    messagingSenderId: '615072854096',
    projectId: 'outdoor-53765',
    storageBucket: 'outdoor-53765.appspot.com',
    iosClientId: '615072854096-0mmann1tbsit6ruljap0vteir3ageot1.apps.googleusercontent.com',
    iosBundleId: 'com.example.outdoor',
  );
}
